name: flutterfire_cli
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: 2.11.0
  cloud_firestore: 4.6.0
  firebase_auth: 4.5.0
  firebase_messaging: 14.5.0
  firebase_crashlytics: 3.2.0
  google_fonts: ^6.2.1
  firebase_core_platform_interface: 4.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true